// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.6
// source: pkg/downloader/proto/oshin_state.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OShinState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                                                                          // 版本号
	Urls          []string               `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`                                                                                 // 下载源 URL 列表
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                                                         // 输出文件名
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`                                                     // 文件总大小（字节）
	ChunkSize     int64                  `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`                                                     // 分片大小（字节）
	Et            string                 `protobuf:"bytes,6,opt,name=et,proto3" json:"et,omitempty"`                                                                                     // 校验信息，格式 "type:value"（如 "md5:abc123"）
	Chunks        []*Chunk               `protobuf:"bytes,7,rep,name=chunks,proto3" json:"chunks,omitempty"`                                                                             // 已完成的分片列表
	Headers       map[string]string      `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // HTTP 自定义请求头
	Protocol      string                 `protobuf:"bytes,9,opt,name=protocol,proto3" json:"protocol,omitempty"`                                                                         // 下载协议（http/https/ftp/sftp）
	Connections   int32                  `protobuf:"varint,10,opt,name=connections,proto3" json:"connections,omitempty"`                                                                 // 最大并发连接数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OShinState) Reset() {
	*x = OShinState{}
	mi := &file_pkg_downloader_proto_oshin_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OShinState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OShinState) ProtoMessage() {}

func (x *OShinState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_downloader_proto_oshin_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OShinState.ProtoReflect.Descriptor instead.
func (*OShinState) Descriptor() ([]byte, []int) {
	return file_pkg_downloader_proto_oshin_state_proto_rawDescGZIP(), []int{0}
}

func (x *OShinState) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OShinState) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *OShinState) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *OShinState) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *OShinState) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *OShinState) GetEt() string {
	if x != nil {
		return x.Et
	}
	return ""
}

func (x *OShinState) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *OShinState) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *OShinState) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *OShinState) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

// Chunk 单个已完成分片的状态
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`       // 分片索引
	Start         int64                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"` // 起始字节位置（含）
	End           int64                  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`     // 结束字节位置（含）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_pkg_downloader_proto_oshin_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_downloader_proto_oshin_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_pkg_downloader_proto_oshin_state_proto_rawDescGZIP(), []int{1}
}

func (x *Chunk) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Chunk) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Chunk) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_pkg_downloader_proto_oshin_state_proto protoreflect.FileDescriptor

const file_pkg_downloader_proto_oshin_state_proto_rawDesc = "" +
	"\n" +
	"&pkg/downloader/proto/oshin_state.proto\x12\n" +
	"downloader\"\x89\x03\n" +
	"\n" +
	"OShinState\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x12\n" +
	"\x04urls\x18\x02 \x03(\tR\x04urls\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\x03R\tchunkSize\x12\x0e\n" +
	"\x02et\x18\x06 \x01(\tR\x02et\x12)\n" +
	"\x06chunks\x18\a \x03(\v2\x11.downloader.ChunkR\x06chunks\x12=\n" +
	"\aheaders\x18\b \x03(\v2#.downloader.OShinState.HeadersEntryR\aheaders\x12\x1a\n" +
	"\bprotocol\x18\t \x01(\tR\bprotocol\x12 \n" +
	"\vconnections\x18\n" +
	" \x01(\x05R\vconnections\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x05Chunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x03R\x03endB/Z-github.com/mogumc/oshind/pkg/downloader/protob\x06proto3"

var (
	file_pkg_downloader_proto_oshin_state_proto_rawDescOnce sync.Once
	file_pkg_downloader_proto_oshin_state_proto_rawDescData []byte
)

func file_pkg_downloader_proto_oshin_state_proto_rawDescGZIP() []byte {
	file_pkg_downloader_proto_oshin_state_proto_rawDescOnce.Do(func() {
		file_pkg_downloader_proto_oshin_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_downloader_proto_oshin_state_proto_rawDesc), len(file_pkg_downloader_proto_oshin_state_proto_rawDesc)))
	})
	return file_pkg_downloader_proto_oshin_state_proto_rawDescData
}

var file_pkg_downloader_proto_oshin_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_downloader_proto_oshin_state_proto_goTypes = []any{
	(*OShinState)(nil), // 0: downloader.OShinState
	(*Chunk)(nil),      // 1: downloader.Chunk
	nil,                // 2: downloader.OShinState.HeadersEntry
}
var file_pkg_downloader_proto_oshin_state_proto_depIdxs = []int32{
	1, // 0: downloader.OShinState.chunks:type_name -> downloader.Chunk
	2, // 1: downloader.OShinState.headers:type_name -> downloader.OShinState.HeadersEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_downloader_proto_oshin_state_proto_init() }
func file_pkg_downloader_proto_oshin_state_proto_init() {
	if File_pkg_downloader_proto_oshin_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_downloader_proto_oshin_state_proto_rawDesc), len(file_pkg_downloader_proto_oshin_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_downloader_proto_oshin_state_proto_goTypes,
		DependencyIndexes: file_pkg_downloader_proto_oshin_state_proto_depIdxs,
		MessageInfos:      file_pkg_downloader_proto_oshin_state_proto_msgTypes,
	}.Build()
	File_pkg_downloader_proto_oshin_state_proto = out.File
	file_pkg_downloader_proto_oshin_state_proto_goTypes = nil
	file_pkg_downloader_proto_oshin_state_proto_depIdxs = nil
}
